language: php
php:
 - 7.3.12
 - hhvm-nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev


 script: phpunit

matrix:
  allow_failures:
    - 7.3.12
 - hhvm-nightly
  fast_finish: true


notifications:
    on_success: never
    on_failure: always
    email: carlosf0505@gmail.com



